[package]
name = "serde-humantime"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[dependencies]
humantime = "1.0"
serde = "1.0"

[dev-dependencies]
serde_derive = "1.0"
serde_json = "1.0"
